version: '3'
services:
    mongo:
        image: mongo
        ports:
         - 27017:27017
        volumes:
         - data-mongo-tendon:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
volumes:
    data-mongo-tendon:
        driver: local